const SIGNUP_STATUS = {
    SUCCESSFUL : 'SIGNUP_SUCCESSFUL',
    USER_EXIST : 'SIGNUP_FAIL_USER_EXIST',
    SERVERERROR: 'SIGNUP_FAIL_SERVERERROR' 
}

const LOGIN_STATUS = {
    SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    NOUSER: 'LOGIN_FAIL_NO_USER',
    INVALID: 'INVALID_PASSWORD',
    NOACCESSTOKEN: 'LOGIN_FAIL_NO_ACCESSTOKEN',
    SERVERERROR: 'LOGIN_FAIL_SERVERERROR',
}

module.exports = {
    SIGNUP_STATUS: SIGNUP_STATUS,
    LOGIN_STATUS: LOGIN_STATUS
}