const SIGNUP_STATUS = {
    SUCCESSFUL : 'SIGNUP_SUCCESSFUL',
    USER_EXIST : 'SIGNUP_FAIL_USER_EXIST',
    UNKNOWN : 'SIGNUP_FAIL_UNKNOWN'
}

const LOGIN_STATUS = {
    SUCCESSFUL : 'LOGIN_SUCCESSFUL',
    NOUSER : 'LOGIN_FAIL_NO_USER',
    NOACCESSTOKEN: 'LOGIN_FAIL_NO_ACCESSTOKEN',
    UNKNOWN: 'LOGIN_FAIL_UNKNOWN' 
}

module.exports = {
    SIGNUP_STATUS: SIGNUP_STATUS,
    LOGIN_STATUS: LOGIN_STATUS
}
