const AUTH_STATUS = {
    //* Successful status
    SIGNUP_SUCCESSFUL: 'SIGNUP_SUCCESSFUL',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    //* Failed status
    SIGNUP_USER_EXIST: 'SIGNUP_FAIL_USER_EXIST',
    LOGIN_INVALID: 'INVALID_PASSWORD',
    LOGIN_NO_USER: 'LOGIN_FAIL_NO_USER',
    LOGIN_NO_ACCESSTOKEN: 'LOGIN_FAIL_NO_ACCESSTOKEN',
    SERVER_ERROR: 'AUTH_FAIL_SERVERERROR',
    UNKNOWN_ERROR: 'AUTH_UNKNOWN_ERROR',
}

module.exports = AUTH_STATUS;