const EVENT_STATUS = {
    //* Successful status
    GET_SUCCESSFUL: 'GET_EVENT_SUCCESSFUL',
    POST_SUCCESSFUL: 'POST_EVENT_SUCCESSFUL',
    DELETE_SUCCESSFUL: 'DELETE_EVENT_SUCCESSFUL',
    UPDATE_SUCCESSFUL: 'UPDATE_EVENT_SUCCSSFUL',
    //* Failed status
    NOT_FOUND: 'EVENT_NOT_FOUND',
    UPDAPE_FAIL: 'UPDATE_EVENT_FAIL',
    DELETE_FAIL: 'DELETE_EVENT_FAIL',
    UPLOAD_FAIL: 'UPLOAD_FILE_FAIL'
}

module.exports = EVENT_STATUS;