const EVENT_STATUS = {
    //* Successful status
    GET_SUCCESSFUL: 'GET_EVENT_SUCCESSFUL',
    POST_SUCCESSFUL: 'POST_EVENT_SUCCESSFUL',
    DELETE_SUCCESSFUL: 'DELETE_EVENT_SUCCESSFUL',
    UPDATE_SUCCESSFUL: 'UPDATE_EVENT_SUCCSSFUL',
    //* Failed status
    NOT_AUTHORIZED: 'EVENT_NOT_AUTHORIZED',
    NOT_FOUND: 'EVENT_NOT_FOUND',
    UPLOAD_FAIL: 'UPLOAD_PHOTOS_FAIL',
    DELETE_FAIL: 'DELETE_PHOTOS_FAIL',
    SERVER_ERROR: 'EVENT_FAIL_SERVERERROR',
    UNKNOWN_ERROR: 'EVENT_UNKNOWN_ERROR',
}

module.exports = EVENT_STATUS;