const GENERAL_STATUS = {
    DATABASE_ERROR: "DATABASE_ERROR",
    NOT_AUTHORIZED: "NOT_AUTHORIZED",
    UPLOAD_FAIL: "UPLOAD_FAIL",
    SERVER_ERROR: "SERVER_ERROR",
    UNKNOWN_ERROR: "UNKNOWN_ERROR"
}

module.exports = GENERAL_STATUS;