const QUESTION_HISTORY_STATUS = {
    //* successful status
    GET_HISTORY_SUCCESSFUL: 'GET_HISTORY_SUCCESSFUL',
    UPDATE_HISTORY_SUCCESSFUL: 'UPDATE_HISTORY_SUCCESSFUL',
    DELETE_HISTORY_SUCCESSFUL: 'DELETE_HISTORY_SUCCESSFUL',
    POST_HISTORY_SUCCESSFUL: 'POST_HISTORY_SUCCESSFUL',
    //* fail status
    POST_HISTORY_FAIL: 'POST_HISTORY_FAIL_NO_USER',
    GET_HISTORY_FAIL: 'GET_HISTORY_FAIL_NO_HISTORY',
    DELETE_HISTORY_FAIL: 'DELETE_HISTORY_FAIL_NO_USER',
    SERVER_ERROR: 'QUESTION_HISTORY_SERVER_ERROR',
}

module.exports = QUESTION_HISTORY_STATUS;