const QUESTION_STATUS = {
    //* successful status
    READ_QUESTION_SUCCESSFUL: 'READ_QUESTION_SUCCESSFUL',
    CREATE_QUESTION_SUCCESSFUL: 'CREATE_QUESTION_SUCCESSFUL',
    CREATE_OPTION_SUCCESSFUL: 'CREATE_OPTION_SUCCESSFUL',
    UPDATE_SUCCESSFUL: 'UPDATE_QUESTION_SUCCESSFUL',
    UPDATE_NO_ENTITY: 'UPDATE_QUESTION_NO_ENTITY',
    //* fail status
    READ_FAIL_NO_QUESTION: 'READ_QUESTION_FAIL_NO_QUESTTION',
    POST_FAIL_INVALID_INPUT: 'POST_QUESTION_FAIL_INVALID_INPUT',
    SERVER_ERROR: 'QUESTION_SERVER_ERROR',
    UNKNOWN_ERROR: 'QUESTION_UNKNOWN_ERROR'
}

module.exports = QUESTION_STATUS;