const USER_STATUS = {
    GET_SUCCESSFUL:'GET_USER_SUCCESSFUL',
    DELETE_SUCCESSFUL: 'DELETE_USER_SUCCESSFUL',
    UPDATE_SUCCESSFUL: 'UPDATE_USER_SUCCESSFUL',
    CREATE_SUCCESSFUL: 'CREATE_USER_SUCCESSFUL',
    SERVER_ERROR: 'USER_FAIL_SERVER_ERROR',
    NO_USER: 'GET_USER_FAIL_NO_USER',
    USER_EXIST: 'CREATE_USER_FAIL_USER_EXIST',
}

module.exports = USER_STATUS;