const USER_STATUS = {
    //* Successful status
    GET_SUCCESSFUL:'GET_USER_SUCCESSFUL',
    CREATE_SUCCESSFUL: 'CREATE_USER_SUCCESSFUL',
    DELETE_SUCCESSFUL: 'DELETE_USER_SUCCESSFUL',
    UPDATE_SUCCESSFUL: 'UPDATE_USER_SUCCESSFUL',
    DELETE_NO_ENTITY: 'DELETE_USER_NO_ENTITY',
    UPDATE_NO_ENTITY: 'UPDATE_USER__NO_ENTITY',
    //* Failed status
    SERVER_ERROR: 'USER_FAIL_SERVER_ERROR',
    NO_USER: 'GET_USER_FAIL_NO_USER',
    INFO_USED: 'UPDATED_USER_FAIL_SOCIALID_OR_EMAIL_USED',
    USER_EXIST: 'CREATE_USER_FAIL_USER_EXIST',
    UNKNOWN_ERROR: 'USER_UNKNOWN_ERROR'
}

module.exports = USER_STATUS;